### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gfrancine** [marconunnari/trello-clone#10]
Hey, I have a fork of this and I want to use it on a personal project, but I can't find a license or a copyright notice and I'm not sure if I'm allowed to do that.

If this project is meant to be open source, maybe you can consider adding a license to avoid confusions about copyright. Otherwise, let me know if I can get in touch. Thanks!

**Comment by marconunnari** [comment]
Hello, I created this project for educational purposes so I didn't think to add a license, I've added the MIT license now, feel free to use it for whatever you want 👍
