### ISSUE TITLE
Problem with cache

### ISSUE THREAD

**Issue by spartaelcid** [marconunnari/trello-clone#8]
Hello,

after i install this trello-clone I have encountered a problem.

If I edit the list from my browser, my colleague does not see the change from his browser.
it is as if the old project cache remains and therefore does not notice that it has been modified!

**Comment by marconunnari** [comment]
Hello,

I'm sorry but this is only the front-end, there isn't a server so the changes won't synchronize between different browsers.

**Comment by AGSAVALIYA** [comment]
How we can add firebase to solve this?
